platform :ios, '6.0'
xcodeproj 'Ornament/Ornament.xcodeproj'
pod 'Mensa', :git => 'https://github.com/jordanekay/Mensa.git', 'https://raw.github.com/jordanekay/Mensa/master/Mensa.podspec'
pod 'TTSwitch', :git => 'https://github.com/jordanekay/TTSwitch.git'
pod 'KGNoise', :git => 'https://github.com/jordanekay/KGNoise.git'
