platform :ios, '5.0'
xcodeproj 'Ornament/Ornament.xcodeproj'
pod 'Mensa', :git => 'https://github.com/jordanekay/Mensa.git'
pod 'TTSwitch', :git => 'https://github.com/jordanekay/TTSwitch.git'
pod 'KGNoise', :git => 'https://github.com/jordanekay/KGNoise.git'
